version: '3.4'

services:
    allegromanager:
        image: ${DOCKER_REGISTRY-}allegromanager
        container_name: AllegroManager
        build:
            context: .
            dockerfile: AllegroManager/Dockerfile
        depends_on:
            db:
                condition: service_healthy
    db:
        image: mcr.microsoft.com/mssql/server:2022-latest
        healthcheck:
            test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -C -Q "SELECT 1" -b -o /dev/null
            interval: 5s
            retries: 2
            start_period: 30s
            timeout: 3s
        container_name: AllegroManagerDB
        environment:
            SA_PASSWORD: "HomeyStyle!23_45"
            ACCEPT_EULA: Y
        ports:
        - 1433:1433
        expose:
        - '1433'
        volumes:
        - my-db:/var/opt/mssql  
        - ./AllegroManager.Database.Build:/sql-scripts
        - ./entrypoint.sh:/entrypoint.sh 
        command: /bin/bash /entrypoint.sh
volumes:
    my-db:    