services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        ENV_VARIABLE: ${ENV_VARIABLE}
        NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        ENV_VARIABLE_KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
        ENV_VARIABLE_KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}
        ENV_VARIABLE_KEYCLOAK_ISSUER: ${KEYCLOAK_ISSUER}
        NEXTAUTH_SECRET: ${AUTH_SECRET}
        NEXTAUTH_URL: ${NEXTAUTH_URL}
    restart: always
    ports:
      - 3000:3000
    networks:
      - my_network

  # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
    external: true
